### PR TITLE
Add mc-backup Sidecar

### PR DESCRIPTION
**Pull request by merkinbob**
Add mc-backup sidecar for minecraft-server.

Ready for testing:
- tar
- rclone
- restic

> Please be careful with Restic, take note of the `HOSTNAME` conflict

Tested:
- [x] tar method
- [ ] rclone method
- [ ] restic method

image

I believe restic and rclone are setup right, but i have no way of testing these

Solves #91

### CODE REVIEW

**Comment by merkinbob** [comment]
is there any interest in rclone or restic for the chart?

**Comment by itzg** [comment]
> is there any interest in rclone or restic for the chart?

People use those methods, but can be included in a follow up PR.

**Comment by merkinbob** [comment]
> > is there any interest in rclone or restic for the chart?
> 
> People use those methods, but can be included in a follow up PR.

in theory restic is done, but i don't know how to test it.  rclone i need to add a config map for.

**Comment by merkinbob** [comment]
> Please take a look at the build failure.

will do

**Comment by merkinbob** [comment]
@itzg I think this now adds restic, and rclone capabilities, i didn't test it tho.  tar still works, linting should pass.

**Comment by merkinbob** [comment]
3rd time the chart?

**Comment by cburza** [comment]
@merkinbob I will attempt to test rclone.

**Comment by cburza** [comment]
@merkinbob I am getting the following error on container startup:
```
time="2022-01-11T18:06:19Z" level=fatal msg="Failed to run sub-command" error="fork/exec /usr/bin/backup: operation not permitted"
```

I have RCON in the server. I am setting no other values for mcbackup other than `enabled: true`.

Do you perhaps know what could be causing it?

**Comment by merkinbob** [comment]
> @merkinbob I am getting the following error on container startup:
> 
> ```
> time="2022-01-11T18:06:19Z" level=fatal msg="Failed to run sub-command" error="fork/exec /usr/bin/backup: operation not permitted"
> ```
> 
> I have RCON enabled in the server. I am setting no other values for mcbackup other than `enabled: true`.
> 
> Do you perhaps know what could be causing it?

my guess is it's not happy with empty dir for the backup volume.  let me check the `deployment.yaml` file a bit.

Below is all i have set in my `values.yaml` file for my argocd deployment.

```
mcbackup:
  enabled: true     

  persistence:
    storageClass: "csi-cephfs-sc"
    backupDir:
      enabled: true
      Size: 500Gi
  ```

**Review by itzg — APPROVED** [review]
Final review looks great! Ready for a merge?

**Comment by merkinbob** [comment]
> Final review looks great! Ready for a merge?

one concern I have about restic is the `HOSTNAME` note on your `mc-backup` docs.  Other than that, I think this is a good start.  I hope someone finds this useful.

**Comment by itzg** [comment]
Just discovered there's a `--hostname`. I wrote up https://github.com/itzg/docker-mc-backup/issues/55 , but I think the chart changes will be good even with that.

**Pull request merged**
