### PR TITLE
set ingress apiversion in accordance to k8s version

### PR DESCRIPTION
**Pull request by ishioni**
Let's not discriminate those with older k8s versions :)
I'll rebase this once #59 hits master

### CODE REVIEW

**Comment by itzg** [comment]
I'm so sorry @ishioni , I just noticed this PR fell through the cracks. If you can resolve the merge conflicts that showed up (sorry again), then I'll be glad to merge this.

**Comment by ishioni** [comment]
I'll take a stab at it at night

**Comment by inductor** [comment]
@ishioni ping just in case you forget this

**Comment by ishioni** [comment]
@itzg Sorry, was moving apartaments. Just pushed an update, this should be ready to go now

**Comment by itzg** [comment]
> Edit: not sure why the linting failed, looks like some node toleration problems?

Yeah, not sure either, but I'm having it re-run the check.

**Comment by itzg** [comment]
I'm not sure why your PR is bumping into lint builder issues, but I do see the github actions are overdue for an upgrade. Do I mind if I push some changes to that to your branch?

**Comment by ishioni** [comment]
Not at all, feel free :)

**Comment by billimek** [comment]
FYI, I'm getting an error trying to upgrade to this version of the chart,

```yaml
Error: template: minecraft/templates/extraports-ing.yaml:7:15: executing "minecraft/templates/extraports-ing.yaml" at <include "minecraft.ingress.apiVersion" .>: error calling include: template: minecraft/templates/_helpers.tpl:19:44: executing "minecraft.ingress.apiVersion" at <.Capabilities.KubeVersion.GitVersion>: nil pointer evaluating interface {}.KubeVersion
```

(ref: https://github.com/billimek/k8s-gitops/runs/3082237605?check_suite_focus=true#step:5:304)

**Comment by ishioni** [comment]
@billimek Which helm version?

**Comment by billimek** [comment]
> @billimek Which helm version?

It looks like [3.5.2](https://github.com/billimek/k8s-gitops/runs/3082237605?check_suite_focus=true#step:2:22)

**Pull request merged**
