### PR TITLE
Add support to see namespace when performing --dry-run

### PR DESCRIPTION
**Pull request by ryanchauvin**
Added support to see namespace in yaml files when performing --dry-run for all charts.

### CODE REVIEW

**Comment by ryanchauvin** [comment]
https://github.com/itzg/minecraft-server-charts/issues/210

**Review by itzg — APPROVED** [review]

**Review by itzg — CHANGES_REQUESTED** [review]
I had forgotten until the lint check ran -- the chart versions need to be bumped.

**Review by itzg — APPROVED** [review]

**Comment by itzg** [comment]
Oh yeah, rcon web admin is broken for some reason. You might need to revert your changes for that chart unless you feel like investigating 😄

**Comment by ryanchauvin** [comment]
I can look into it, I just sent you an email for more details around the issue.




________________________________

**Comment by itzg** [comment]
It's still reporting merge conflicts

image

**Review by itzg — APPROVED** [review]

**Comment by toddejohnson** [comment]
It looks like the helm chart is struggling and I don't see this field in `values.yaml`:
```
Helm upgrade failed for release mc/mc1 with chart minecraft@4.22.1: template: minecraft/templates/extraports-svc.yaml:10:24: executing "m
inecraft/templates/extraports-svc.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```
I'm already `targetNamespace: mc` in `kind: HelmRelease`. Do I need to be more blunt with it?

**Comment by itzg** [comment]
@ryanchauvin this might have caused a regression. Please see discussion here

https://discord.com/channels/660567679458869252/660571171732848651/1279147295518101617

> It looks like the helm chart is struggling and I don't see this field in `values.yaml`:
```
Helm upgrade failed for release mc/mc1 with chart minecraft@4.22.1: template: minecraft/templates/extraports-svc.yaml:10:24: executing "m
inecraft/templates/extraports-svc.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```
I'm already `targetNamespace: mc` in `kind: HelmRelease`. Do I need to be more blunt with it?

**Comment by itzg** [comment]
@toddejohnson please try out this chart release

https://github.com/itzg/minecraft-server-charts/releases/tag/minecraft-4.22.2

**Comment by toddejohnson** [comment]
Applied without issues. Thank you for the quick fix @ryanchauvin!!! 

Whew I was sweating for a bit as I don't know how to get Flux to reference a git tag helm chart. I saw it published to the normal URL and it has applied without issues.

**Comment by ryanchauvin** [comment]
Sorry for the oversight, glad it’s working now 😊

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
