### PR TITLE
 Allow adding sidecarContainers

### PR DESCRIPTION
**Pull request by Robbilie**
https://github.com/itzg/minecraft-server-charts/pull/96

Changed the branch in my repo and that didnt go as planned…

### CODE REVIEW

**Comment by Robbilie** [comment]
I would consider adding replica configuration to the chart because i have a usecase for that and the chart currently doesnt support it, any thoughts?

**Comment by itzg** [comment]
> I would consider adding replica configuration to the chart because i have a usecase for that and the chart currently doesnt support it, any thoughts?

I'm curious how you were thinking of using replicas? Since the Minecraft server isn't aware of horizontally scaling I'm thinking it would step on the data of the other replicas.

**Review by itzg — APPROVED** [review]

**Comment by Robbilie** [comment]
I am building a meshing & sharding proxy and am syncing blockchanges using rcon, the sidecar will patch a world up to a state where it matches the other ones :)

**Comment by Robbilie** [comment]
https://github.com/itzg/minecraft-server-charts/pull/98

**Comment by ChipWolf** [comment]
> I am building a meshing & sharding proxy and am syncing blockchanges using rcon, the sidecar will patch a world up to a state where it matches the other ones :)

@Robbilie got a repo on the go for that project?

**Comment by Robbilie** [comment]
I do, it's in a privately hosted gitlab instance though :P I also switched to creating my own operator for that project. If you are interested in working on such a project let me know, discord name would be Robbilie#1405 :) same goes for others (including itzg :) ), the project doesn't have to live in a private repo forever either...

**Pull request merged**
