### PR TITLE
mc-router: Add extraServiceSpec for customizing services

### LINKED ISSUE #215: Add support for mc-router service extra specs
Such feature is already present for minecraft-server
https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/templates/minecraft-svc.yaml#L74-L76

In my case I need to add dualstack on the service but I am limited by the helm chart

### PR DESCRIPTION
**Pull request by Edouard127**
This pull request adds the `extraServiceSpec` field inside the `service` object in the values.yaml
Allows for more flexibility on the user end
Closes #215

### CODE REVIEW

**Review by itzg — COMMENTED** [review]
Thanks! Can you also bump the chart version?

**Comment by Edouard127** [comment]
Sure thing, I also noticed that the appVersion does not match the current release for itzg/mc-router
https://github.com/itzg/mc-router/releases/latest
Should I bump this version too ?

**Comment by itzg** [comment]
> I also noticed that the appVersion does not match the current release for itzg/mc-router
> 
> https://github.com/itzg/mc-router/releases/latest
> 
> Should I bump this version too ?

Nah, it doesn't need to match up.

**Comment by Edouard127** [comment]
All good then !

**Pull request merged**
